### PR TITLE
Added GitHub for Projects Resource

### PR DESCRIPTION
**Pull request by BrainonSilicon**
Added presentation slides from a meeting on 26/05/2022 about what features github offers for project management and how it could be used to support the AIM RSF workstreams.

### CODE REVIEW

**Comment by BrainonSilicon** [comment]
Hiya team! 

I gave a small presentation on the features that GitHub projects offers for managing projects. I thought it might be a good resources that others can reuse. 

Let me know if:
- [ ] you have any suggested edits
- [ ] this folder was the correct place to put this resource

**Review by EKaroune — APPROVED** [review]
Thanks Sophia - do you mind also making the presentation as a pdf and putting in this repo too. 

It would be good to start a presentations folder for any useful presentation slides we want to share here.

**Comment by BrainonSilicon** [comment]
> Thanks Sophia - do you mind also making the presentation as a pdf and putting in this repo too.
> 
> It would be good to start a presentations folder for any useful presentation slides we want to share here.

Done and done ✨

**Comment by BrainonSilicon** [comment]
This PR and branch is to be marked as closed and resolved by PR #69 as presentations have been placed in a resources folder that was added as part of PR #64.

**Pull request closed without merging**
